services:
  app:
    container_name: mobile-terminal-application-development-app
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.development
    volumes:
      - type: bind
        source: ../
        target: /workspaces/mobile-terminal-application-development/
    networks:
      - mobile-terminal-application-development
    tty: true

networks:
  mobile-terminal-application-development:
    external: false
